ProyectoGAE/src/main/java/com/Beans/AgendaBean.java
package com.Beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;
import javax.servlet.http.HttpServletRequest;

import com.google.appengine.api.appidentity.AppIdentityService;
import com.google.appengine.api.appidentity.AppIdentityServiceFactory;
import com.google.appengine.api.users.User;
import com.google.appengine.api.users.UserService;
import com.google.appengine.api.users.UserServiceFactory;

import consultas.EventoUtils;
import consultas.UsuarioUtils;
import entidadesBD.Evento;
import entidadesBD.Notificacion;
import entidadesBD.Usuario;

@ManagedBean
@SessionScoped
public class AgendaBean implements Serializable {

	private static final long serialVersionUID = 1L;
	private List<Evento> listaEventos;
	private List<Evento> listaEventosPerfil;
	private Evento evento;
	private Usuario usuario;
	private String email;
	private String filtro;
	private double precioMax;
	private String correoUsuarioBuscado;
	private Usuario usuarioBuscado;
	private boolean mensajeErrorBusqueda;
	private List<Notificacion> listaNotificaciones;
	private String correoUsuario;
	private String mensajeError = "";

	private List<Evento> listaGustados;
	private List<Evento> listaSeguidos;
	private List<Evento> listaCreados;
	private List<Evento> listaValidados;// lista eventos validados por el usuario en sesion
	private List<String> listaDireccionesEventos = new ArrayList<>();

	@PostConstruct
	public void init() {
		listaEventos = filtrado(" ");
		cargarDirecciones();
		filtro = "";
		precioMax = 0.0;
		setMensajeError(mensajeError);
		mensajeErrorBusqueda = false;
		// mensajeError = "Esto es una prueba 1";
		// email="javycg95@gmail.com";
		// iniciarSesion();


	}

	public AgendaBean() {
	}

	public boolean estaConectado() {
		UserService userService = UserServiceFactory.getUserService();
		iniciarSesion();
		return userService.isUserLoggedIn();
	}
	public boolean estaConectadoFiltrado() {
		UserService userService = UserServiceFactory.getUserService();
		iniciarSesion();
		
		return userService.isUserLoggedIn() && filtro.equals("precio");
	}
	public boolean esPeriodista() {
		UserService userService = UserServiceFactory.getUserService();
		if (userService.isUserLoggedIn()) {
			if (usuario != null) {
				return usuario.getTipousuario().equals("PE");
			}
		}
		return false;
	}

	/*
	 * public boolean hayNotificaciones() { listaNotificaciones(); if
	 * (listaNotificaciones == null) { return false; } return
	 * !listaNotificaciones.isEmpty(); }
	 */

	public String filtrar() {
		listaEventos = filtrado(filtro);
		cargarDirecciones();
		return "agendaHome";
	}
	
	public void cargarDirecciones() {
		if (!listaDireccionesEventos.isEmpty()) {
			listaDireccionesEventos.clear();
		}				
		if (!listaEventos.isEmpty()) {
			for (Evento evento : listaEventos) {
				listaDireccionesEventos.add(evento.getDireccion());
			}
		}
	}

	public String volverAgendaInicio() {
		precioMax = 0.0;
		listaEventos = EventoUtils.getEventosValidados();
		return "agendaHome";
	}

	public String filtradoPerfil() {
		listaEventosPerfil = filtrado(filtro);
		return "verMiPerfil";
	}

	public String iniciarSesion() {
		UserService userService = UserServiceFactory.getUserService();
		if (userService.isUserLoggedIn()) {
			User user = userService.getCurrentUser();
			email = user.getEmail();
			usuario = UsuarioUtils.buscarUsuario(email);
			if(usuario == null) {
				UsuarioUtils.put(email, "Nombre", "Apellidos", "US", "", "");
				usuario = UsuarioUtils.buscarUsuario(email);
			}
		}
		return "agendaHome";
	}

	public String cerrarSesion() {
		email = "";
		usuario = null;
		return "agendaHome";
	}

	public String getLoginUrl() {
		UserService userService = UserServiceFactory.getUserService();
		return userService.createLoginURL("/faces/agendaHome.xhtml");
	}

	public String getLogoutUrl() {
		UserService userService = UserServiceFactory.getUserService();
		return userService.createLogoutURL("/faces/agendaHome.xhtml");
	}

	private List<Evento> filtrado(String filtro) {
		switch (filtro) {

		case "tag":
			return buscarEventoPorTag();
		case "precio":
			return buscarPorPrecioMax();
		case "validados":
			return buscarValidadosPorAlguien();
		case "creados":
			return buscarCreadosPorAlguien();
			/*
		case "seguidos":
			return listaSeguidos();
		case "gustados":
			return listaGustados();
		case "cercano":
			return encontrarEventosCercanos(coordenadas);
*/
		default:
			return EventoUtils.getEventosValidados();
		}
	}

	private List<Evento> buscarEventoPorTag() {
		return EventoUtils.getEventosPorTag(usuario.getTag());
	}
	private List<Evento> buscarCreadosPorAlguien() {
		return EventoUtils.getEventosCreadosPorAlguien(usuario.getKey());
	}
	private List<Evento> buscarValidadosPorAlguien() {
		return EventoUtils.getEventosValidadosPorAlguien(usuario.getKey());
	}
	private List<Evento> buscarPorPrecioMax() {

		return EventoUtils.getEventosPorPrecioMax(precioMax);
	}

	public List<Notificacion> obtenerNotificaciones(Usuario usuario) {
		return new ArrayList<Notificacion>();
	}

	public String crearCuenta() {
		return "crearUsuario";
	}

	public String editarCuenta() {
		return "editarCuenta";
	}

	public String irVerEvento() {
		String title = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("title");
		Evento e = EventoUtils.buscarEvento(title);
		setEvento(e);
		return "verEvento";
	}

	public String irCrearEvento() {

		return "crearEvento";
	}

	public String irMiPerfil() {
		listaEventosPerfil = new ArrayList<Evento>();
		return "verMiPerfil";
	}

	public String irBusqueda() {
		usuarioBuscado = UsuarioUtils.buscarUsuario(correoUsuarioBuscado);
		if (usuarioBuscado == null) {
			mensajeErrorBusqueda = true;
			return "agendaHome";
		}
		return "verUsuario";
	}

	public String irEventosNoValidados() {
		return "verEventosNoValidados";
	}

	public String irMisNotificaciones() {
		return "verNotificaciones";
	}

	public List<Evento> getListaEventos() {
		return listaEventos;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public List<Evento> getListaEventosPerfil() {
		return listaEventosPerfil;
	}

	public void setListaEventosPerfil(List<Evento> listaEventosPerfil) {
		this.listaEventosPerfil = listaEventosPerfil;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Evento getEvento() {
		return evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public List<Evento> getListaGustados() {
		return listaGustados;
	}

	public void setListaGustados(List<Evento> listaGustados) {
		this.listaGustados = listaGustados;
	}

	public List<Evento> getListaSeguidos() {
		return listaSeguidos;
	}

	public void setListaSeguidos(List<Evento> listaSeguidos) {
		this.listaSeguidos = listaSeguidos;
	}

	public List<Evento> getListaCreados() {
		return listaCreados;
	}

	public void setListaCreados(List<Evento> listaCreados) {
		this.listaCreados = listaCreados;
	}

	public List<Notificacion> getListaNotificaciones() {
		return listaNotificaciones;
	}

	public void setListaNotificaciones(List<Notificacion> listaNotificaciones) {
		this.listaNotificaciones = listaNotificaciones;
	}

	public List<Evento> getListaValidados() {
		return listaValidados;
	}

	public void setListaValidados(List<Evento> listaValidados) {
		this.listaValidados = listaValidados;
	}

	public List<String> getListaDireccionesEventos() {
		return listaDireccionesEventos;
	}

	public void setListaDireccionesEventos(List<String> listaDireccionesEventos) {
		this.listaDireccionesEventos = listaDireccionesEventos;
	}

	public void setListaEventos(List<Evento> listaEventos) {
		this.listaEventos = listaEventos;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getCorreoUsuario() {
		return correoUsuario;
	}

	public void setCorreoUsuario(String correoUsuario) {
		this.correoUsuario = correoUsuario;
	}

	public String getMensajeError() {
		return mensajeError;
	}

	public void setMensajeError(String mensajeError) {
		this.mensajeError = mensajeError;
	}

	public String getFiltro() {
		return filtro;
	}

	public void setFiltro(String filtro) {
		this.filtro = filtro;
	}

	public double getPrecioMax() {
		return precioMax;
	}

	public void setPrecioMax(double precioMax) {
		this.precioMax = precioMax;
	}

	public String getCorreoUsuarioBuscado() {
		return correoUsuarioBuscado;
	}

	public void setCorreoUsuarioBuscado(String correoUsuarioBuscado) {
		this.correoUsuarioBuscado = correoUsuarioBuscado;
	}

	public Usuario getUsuarioBuscado() {
		return usuarioBuscado;
	}

	public void setUsuarioBuscado(Usuario usuarioBuscado) {
		this.usuarioBuscado = usuarioBuscado;
	}

	public boolean getMensajeErrorBusqueda() {
		return mensajeErrorBusqueda;
	}
}

ProyectoGAE/src/main/java/com/Beans/CrearEventoBean.java
package com.Beans;

import java.util.Date;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.inject.Inject;

import consultas.EventoUtils;
import entidadesBD.Evento;
import entidadesBD.Usuario;

@ManagedBean
@RequestScoped
public class CrearEventoBean {

	@ManagedProperty("#{agendaBean}")
	private AgendaBean agendaBean;
	@ManagedProperty("#{agendaBean.usuario}")
	private Usuario usuario;
	private String titulo;
	private String descripcion;
	private String preferencias;
	private float precio;
	private Date fechaInicio;
	private Date fechaFin;
	private String direccion;
	private Usuario validador;

	public CrearEventoBean() {
	}

	public String doCrear() {
		if (usuario.getTipousuario().equals("US")) {
			EventoUtils.put(titulo, descripcion, preferencias, precio, fechaInicio, fechaFin, false, null,
					usuario.getKey(), direccion);
		} else {
			EventoUtils.put(titulo, descripcion, preferencias, precio, fechaInicio, fechaFin, true,
					usuario.getKey(), usuario.getKey(), direccion);
		}
		agendaBean.filtrar();
		return "agendaHome";
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getPrecio() {
		return precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
	}

	public AgendaBean getAgendaBean() {
		return agendaBean;
	}

	public void setAgendaBean(AgendaBean agendaBean) {
		this.agendaBean = agendaBean;
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Usuario getValidador() {
		return validador;
	}

	public void setValidador(Usuario validador) {
		this.validador = validador;
	}

	public String getPreferencias() {
		return preferencias;
	}

	public void setPreferencias(String preferencias) {
		this.preferencias = preferencias;
	}
}

ProyectoGAE/src/main/java/com/Beans/CrearUsuarioBean.java
package com.Beans;

import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

import consultas.UsuarioUtils;
import entidadesBD.Usuario;

@ManagedBean
@RequestScoped
public class CrearUsuarioBean {

	private String nombre;
	private String apellidos;
	private String email;
	private String direccion;
	private String tag;
	private String mensajeError;

	public CrearUsuarioBean() {
	}

	public String crearUsuario() {
		UsuarioUtils.put(email, nombre, apellidos, "US", tag, direccion);
		return "agendaHome";
	}

	public String getMensajeError() {
		return mensajeError;
	}

	public void setMensajeError(String mensajeError) {
		this.mensajeError = mensajeError;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getTag() {
		return tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}

ProyectoGAE/src/main/java/com/Beans/EditarEventoBean.java
package com.Beans;

import java.util.Date;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import consultas.EventoUtils;
import entidadesBD.Evento;
import entidadesBD.Usuario;

@ManagedBean
@RequestScoped
public class EditarEventoBean {

	@ManagedProperty("#{agendaBean}")
	private AgendaBean agendaBean;
	@ManagedProperty("#{verEventoBean.usuario}")
	private Usuario usuario;
	@ManagedProperty("#{verEventoBean.evento}")
	private Evento evento;
	private String titulo;
	private String descripcion;
	private String[] tag;
	private float precio;
	private Date fechaInicio;
	private Date fechaFin;
	private String direccion;
	private boolean validado;
	private Usuario validador;
	private String tags;

	public EditarEventoBean() {
	}

	@PostConstruct
	public void init() {
		titulo = evento.getTitulo();
		descripcion = evento.getDescripcion();
		tags = evento.getTag();
		tagsToArray();
		precio = (float) evento.getPrecio();
		fechaInicio = evento.getFechaInicio();
		fechaFin = evento.getFechaFin();
		direccion = (String) evento.getDireccion();
		//this.setTag(evento.getTag().split(";"));
	}

	public void tagsToArray() {
		if (evento.getTag() != null) {
			tag = evento.getTag().split(";");
		} else {
			tag = new String[1];
			tag[0] = "";
		}
	}

	public String doEditar() {
		EventoUtils.edit(evento);
		agendaBean.filtrar();
		return "agendaHome";
	}

	public void deleteOneTag(String tag) {
		/*tagsUpdated = "";
		tagsUpdated = evento.getTag().replace(tag + ";", "");
		EventoUtils.put(titulo, tagsUpdated, descripcion, precio, fechaInicio, fechaFin, validado, validador.getKey(),
				usuario.getKey(), latitud, longitud, direccion);
		evento = EventoUtils.search(evento.key);
		tagsToArray();*/
		
		//Hay que modificarlo, lo de arriba no sirve
	}

	public void addOneNewTag() {
		/*tagsUpdated = "";
		if (evento.getTag().length() == 0) {
			tagsUpdated = nuevaPreferencia + ";";
		} else {
			tagsUpdated = evento.getTag() + nuevaPreferencia + ";";
		}
		EventoUtils.put(titulo, tagsUpdated, descripcion, precio, fechaInicio, fechaFin, validado, validador.getKey(),
				usuario.getKey(), latitud, longitud, direccion);
		evento = EventoUtils.search(evento.key);
		tagsToArray();*/
		
		//Hay que modificarlo, lo de arriba no sirve
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Evento getEvento() {
		return evento;
	}

	public void setEvento(Evento evento) {
		this.evento = evento;
	}

	public String getTitulo() {
		return titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
		evento.setTitulo(titulo);
	}

	public String getDescripcion() {
		return descripcion;
		
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
		evento.setDescripcion(descripcion);
	}

	public String getTags() {
		return tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
		evento.setTag(tags);
	}

	public float getPrecio() {
		return precio;
	}

	public void setPrecio(float precio) {
		this.precio = precio;
		evento.setPrecio(precio);
	}

	public Date getFechaInicio() {
		return fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
		evento.setFechaInicio(fechaInicio);
	}

	public Date getFechaFin() {
		return fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
		evento.setFechaFin(fechaFin);
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
		evento.setDireccion(direccion);
	}

	public boolean isValidado() {
		return validado;
	}

	public void setValidado(boolean validado) {
		this.validado = validado;
	}

	public Usuario getValidador() {
		return validador;
	}

	public void setValidador(Usuario validador) {
		this.validador = validador;
	}
	public String volverAgendaInicio() {		
		agendaBean.setListaEventos(EventoUtils.getEventosValidados());
		agendaBean.cargarDirecciones();
		agendaBean.setPrecioMax(0.0);
		return "agendaHome";
	}

	public AgendaBean getAgendaBean() {
		return agendaBean;
	}

	public void setAgendaBean(AgendaBean agendaBean) {
		this.agendaBean = agendaBean;
	}
	
}

ProyectoGAE/src/main/webapp/agendaHome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:b="http://bootsfaces.net/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
<h:head>
	<title>Agenda Home</title>
	<script type="text/javascript"
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
	<script type="text/javascript"
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCCby4jIW8ItkYOFcz2DbdN_4F1_ei17s8"></script>
	<script type="text/javascript">
		function volverInicio() {

			var jsfCommandLink = document.getElementById("botonInicio:link");
			jsfCommandLink.click();

		}

		function mostrarMapa() {
			var geocoder = new google.maps.Geocoder();

			var listaDirecciones = "#{agendaBean.listaDireccionesEventos}";

			var stringDirecciones = listaDirecciones.substring(1,
					listaDirecciones.length - 1);

			var direcciones = stringDirecciones.split(",")

			var mapa = new google.maps.Map(document.getElementById('map'), {
				center : {
					lat : 36.7183391,
					lng : -4.51930
				},
				zoom : 11
			});

			geocoder
					.geocode(
							{
								'address' : 'Calle Larios'
							},
							function(results, status) {
								if (status === google.maps.GeocoderStatus.OK) {
									mapa
											.setCenter(results[0].geometry.location);
								} else {
									alert('Geocode was not successful for the following reason: '
											+ status);
								}
							});
			var i = direcciones.length;
			while (i--) {
				geocoder
						.geocode(
								{
									'address' : direcciones[i]
								},
								function(results, status) {
									if (status === google.maps.GeocoderStatus.OK) {
										var marker = new google.maps.Marker(
												{
													map : mapa,
													position : results[0].geometry.location
												});
										mapa
												.setCenter(results[0].geometry.location);
									} else {
										alert('Geocode was not successful for the following reason: '
												+ status);
									}
								});
			}
		}
		window.onload = mostrarMapa;
	</script>
</h:head>
<h:body>

	<h:form id="botonInicio">
		<h:commandLink id="link" style="display: none"
			action="#{agendaBean.volverAgendaInicio()}" value="click" />
	</h:form>

	<b:container>
		<b:row>
			<b:column>
				<b:navBar brand="AppSur" onclick="volverInicio()">
					<b:navbarLinks pull="right" style="padding-right: 20px">
						<h:form rendered="#{!agendaBean.estaConectado()}">
							<a href="#{agendaBean.loginUrl}" class="btn btn-default">Iniciar
								Sesion</a>
							<h:outputText value="#{agendaBean.mensajeError}"
								style="color: red" />
						</h:form>
						<b:form>
							<b:commandButton value="Crear cuenta"
								action="#{agendaBean.crearCuenta()}"
								rendered="#{!agendaBean.estaConectado()}" />
						</b:form>
						<h:form>
							<b:commandButton value="Mi perfil"
								action="#{agendaBean.irMiPerfil()}"
								rendered="#{agendaBean.estaConectado()}" />
						</h:form>
						<h:form rendered="#{agendaBean.estaConectado()}">
							<a href="#{agendaBean.logoutUrl}" class="btn btn-default">Cerrar
								Sesion</a>
							<h:outputText value="#{agendaBean.mensajeError}"
								style="color: red" />
						</h:form>
					</b:navbarLinks>
				</b:navBar>
			</b:column>
		</b:row>
		<b:row>
			<b:column span="6" style="padding-left: 20px">
				<b:row>
					<b:column>
						<div>
							<h:form>
								<h:panelGroup id="selectInputPanel">
									<h:inputText id="inputFiltro" style="float: right"
										value="#{agendaBean.precioMax}" size="3"
										rendered="#{agendaBean.estaConectadoFiltrado()}"
										validatorMessage="El valor debe estar entre 0.0 y 5000.0">
										<f:validateDoubleRange minimum="0.0" maximum="5000.0"
											for="inputFiltro" />
									</h:inputText>
								</h:panelGroup>
								<h:commandButton style="float: right" value="Filtrar"
									action="#{agendaBean.filtrar()}"
									rendered="#{agendaBean.estaConectado()}" />

								<h:selectOneListbox id="selecFiltr" style="float: right"
									value="#{agendaBean.filtro}" size="1"
									rendered="#{agendaBean.estaConectado()}">
									<f:selectItem itemValue=" " itemLabel="Defecto" />
									<f:selectItem itemValue="tag" itemLabel="TAG" />
									<f:selectItem itemValue="precio" itemLabel="Precio" />
									<f:ajax render="selectInputPanel" />
								</h:selectOneListbox>

								<h:message id="m1" for="inputFiltro"
									style="color:red; float: right" />

							</h:form>
							<h:form>
								<b:dataTable language="es" page-length="5" page-length-menu="5,10,20"
									id="table" value="#{agendaBean.listaEventos}" var="evento"
									border="1">
									<f:facet name="header">
										<tr>
											<th colspan="1" rowspan="2">Titulo</th>
											<th colspan="1" rowspan="2">Precio</th>
											<th colspan="2">Fecha</th>
										</tr>
										<tr>
											<th>Inicio</th>
											<th>Fin</th>
										</tr>
									</f:facet>
									<h:column>
										<h:commandLink value="#{evento.titulo}"
											action="#{verEventoBean.irVerEvento()}">
											<f:param name="title" value="#{evento.titulo}" />
										</h:commandLink>
									</h:column>
									<b:column>
										<h:outputLabel value="#{evento.precio}€" />
									</b:column>
									<b:column>
										<b:datepicker disabled="true" mode="popup"
											value="#{evento.fechaInicio}" />
									</b:column>
									<b:column>
										<b:datepicker disabled="true" mode="popup"
											value="#{evento.fechaFin}" />
									</b:column>
								</b:dataTable>
							</h:form>
						</div>
					</b:column>
				</b:row>
				<br></br>
				
				
				<b:row>

					<b:column>
						<h:form>
							<b:commandButton value="Crear evento"
								action="#{agendaBean.irCrearEvento()}"
								rendered="#{agendaBean.estaConectado()}" />
						</h:form>
					</b:column>
					<b:column>
						<h:form>
							<b:commandButton value="Ver eventos no validados"
								action="#{agendaBean.irEventosNoValidados()}"
								rendered="#{agendaBean.esPeriodista()}" />
						</h:form>
					</b:column>
				</b:row>
			</b:column>
			<b:column span="2">
				<div id="map" style="width: 500px; height: 350px; border: solid;" />
			</b:column>
		</b:row>
	</b:container>
</h:body>
</html>

ProyectoGAE/src/main/webapp/myHello.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">
 
<h:head>
	<title>GAE + JSF</title>
</h:head>
<h:body>
	<h1>Google App Engine + JSF 2.2 example - hello.xhtml</h1>
	<h:form>
		<h:inputText value="#{helloBean.name}"></h:inputText>
		<h:commandButton value="Welcome Me" action="welcome"></h:commandButton>
	</h:form>
	<h:outputText value="#{helloBean.name}"/>
</h:body>
</html>